on: push

jobs:
    foo:
        runs-on: windows-latest
        strategy:
            matrix:
                a: [1,2,3,4,5,6,7,8,9,0]
            fail-fast: false
        steps:
            - uses: actions/checkout@v4
            - name: install pyprojectx & pdm and print env info
              run: |
                ./pw pdm info
                ./pw pdm info --env
            - run: ./pw pdm install -v
            - uses: actions/upload-artifact@v4
              with:
                  path: C:/Users/runneradmin/AppData/Local/pdm/pdm/Logs